# Generated by Django 5.2.7 on 2025-10-23 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='author',
            field=models.CharField(default='UX-themes', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='live_preview',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.FloatField(default=4.5),
        ),
        migrations.AddField(
            model_name='product',
            name='sales',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('weekly', 'This Week'), ('monthly', 'This Month')], default='weekly', max_length=50),
        ),
    ]
