# Generated by Django 5.2.7 on 2025-10-23 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordPressSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='WordPress Themes', max_length=100)),
                ('description', models.TextField(default='Discover premium WordPress themes crafted by top designers and developers. Each theme is carefully reviewed for quality, performance, and design excellence.')),
                ('image', models.ImageField(blank=True, null=True, upload_to='wordpress/')),
            ],
        ),
    ]
