# Generated by Django 5.2.7 on 2025-10-23 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_wordpresssection'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('author', models.CharField(default='UX-themes', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('rating', models.FloatField(default=0)),
                ('sales', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='themes/')),
                ('category', models.CharField(choices=[('WordPress', 'WordPress'), ('HTML', 'HTML'), ('UI', 'UI Templates'), ('Plugins', 'Plugins')], default='WordPress', max_length=50)),
                ('features', models.TextField(blank=True)),
                ('compatibility', models.CharField(blank=True, max_length=100)),
                ('is_best_seller', models.BooleanField(default=False)),
                ('is_popular', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
