# Generated by Django 5.2.7 on 2025-10-23 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_themeproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='themeproduct',
            name='category',
            field=models.CharField(choices=[('Business', 'Business'), ('Portfolio', 'Portfolio'), ('Blog', 'Blog'), ('E-Commerce', 'E-Commerce'), ('Landing Page', 'Landing Page')], default='WordPress', max_length=50),
        ),
    ]
