# Generated by Django 5.2.7 on 2025-10-23 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_themeproduct_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='themeproduct',
            name='rating',
            field=models.FloatField(default=4),
        ),
        migrations.AlterField(
            model_name='themeproduct',
            name='sales',
            field=models.PositiveIntegerField(default=205),
        ),
    ]
