# Generated by Django 5.2.7 on 2025-10-23 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_themeproduct_rating_alter_themeproduct_sales'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('rating', models.FloatField(default=0)),
                ('sales', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(upload_to='templates/')),
                ('is_featured', models.BooleanField(default=False)),
            ],
        ),
    ]
