# Generated by Django 5.2.7 on 2025-10-24 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_templateitem_delete_templateproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='UITemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('author', models.CharField(default='UX-themes', max_length=255)),
                ('image', models.ImageField(upload_to='ui_templates/')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('rating', models.FloatField(default=5.0)),
                ('sales', models.PositiveIntegerField(default=0)),
                ('is_ui_template', models.BooleanField(default=False)),
                ('is_best_seller', models.BooleanField(default=False)),
                ('is_top_seller', models.BooleanField(default=False)),
                ('is_top_clean_item', models.BooleanField(default=False)),
            ],
        ),
    ]
