# Generated by Django 5.2.7 on 2025-10-24 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_uitemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uitemplate',
            name='price',
            field=models.DecimalField(decimal_places=2, default=99, max_digits=6),
        ),
        migrations.AlterField(
            model_name='uitemplate',
            name='rating',
            field=models.FloatField(default=4.0),
        ),
        migrations.AlterField(
            model_name='uitemplate',
            name='sales',
            field=models.PositiveIntegerField(default=205),
        ),
    ]
