# Generated by Django 5.2.7 on 2025-10-30 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_payment_cvv_alter_payment_expiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('author', models.CharField(default='UX-themes', max_length=255)),
                ('image', models.ImageField(upload_to='ui_templates/')),
                ('price', models.DecimalField(decimal_places=2, default=99, max_digits=6)),
                ('rating', models.FloatField(default=4.0)),
                ('sales', models.PositiveIntegerField(default=205)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_trending', models.BooleanField(default=False)),
                ('is_best_seller', models.BooleanField(default=False)),
                ('is_new_arrival', models.BooleanField(default=False)),
            ],
        ),
    ]
