# Generated by Django 5.2.7 on 2025-10-31 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_hometemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('rating', models.FloatField(default=0)),
                ('sales', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(upload_to='products/')),
                ('live_preview', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
