# Generated by Django 5.2.7 on 2025-10-31 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_homeproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeproduct',
            name='is_featured_themes',
            field=models.BooleanField(default=False),
        ),
    ]
