# Generated by Django 5.2.7 on 2025-10-31 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_homeproduct_is_featured_themes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeproduct',
            name='author',
            field=models.CharField(default='UX-themes', max_length=100),
        ),
        migrations.AlterField(
            model_name='homeproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, default=99, max_digits=6),
        ),
    ]
