# Generated by Django 5.2.7 on 2025-10-31 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_homeproduct_author_alter_homeproduct_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeproduct',
            name='rating',
            field=models.FloatField(default=4),
        ),
        migrations.AlterField(
            model_name='homeproduct',
            name='sales',
            field=models.PositiveIntegerField(default=205),
        ),
    ]
